spring.jpa.properties.hibernate.format_sql=true

# ===========================
# MySQL Database Configuration
# ===========================
# Use environment variables with local dev defaults as fallback
#spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/userdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull}
spring.datasource.url=${DB_URL:jdbc:mysql://mysql-service:3306/userdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===========================
# Connection Pool (HikariCP)
# ===========================
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.connection-test-query=SELECT 1

# ===========================
# JPA / Hibernate
# ===========================
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# MySQL Dialect (Optional for Hibernate 6+)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===========================
# H2 Console
# ===========================
spring.h2.console.enabled=false

app.admin.username=admin
app.admin.first-name=System
app.admin.last-name=Admin
app.admin.email=admin@gmail.com
app.admin.password=Admin@123
app.admin.role=ROLE_ADMIN

# JWT Configuration
jwt.secret=WFslh6t/1ChSPLHbdh2VvsS7f8Ds+NjB/xSNGx8qqRzLycFgo3J3xdRR5E2ywm7JJ/qJS07iumhz5vND4443sg==
#jwt.expiration=86400000
jwt.expiration=3600000
